name: SML Bug Report Template
description: To report any SML related bug
title: "[Bug]: "
body:
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of bug would you like to report?
      multiple: false
      options:
        - Build/Install
        - Performance
        - Support
        - Usability
        - Documentation
        - Currentness/Accuracy
        - Others
    validations:
      required: true
  - type: dropdown
    id: sub-area
    attributes:
      label: Modules Involved
      description: Which modules are involved in this issue?
      multiple: true
      options:
        - SML algorithm
        - Documentation/Tutorial/Example
        - Others
    validations:
      required: true
  - type: dropdown
    id: head
    attributes:
      label: Have you reproduced the bug with SML HEAD?
      description: It is strongly suggested that you have reproduced the bug
        with latest SML code
      options: ["Yes", "No"]
    validations:
      required: true
  - type: dropdown
    id: search
    attributes:
      label: Have you searched existing issues?
      description: To prevent duplicated reports, it is strongly suggested that you search existing issues first.
      options: ["Yes", "No"]
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SML Version
      description: pip version if installed from package, commit id if build
        from source
      placeholder: e.g., SML 0.1.0b0
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: OS Platform and Distribution
      placeholder: e.g., Linux Ubuntu 22.04
    validations:
      required: true
  - type: input
    id: Python
    attributes:
      label: Python Version
      placeholder: e.g., 3.10
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Current Behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Standalone code to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum
        necessary to generate the problem. If possible, please share a link to
        Jupyter/any notebook.
      placeholder: Tell us what you see!
      value: print("A bug")
      render: Python
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be
        automatically formatted into code, so no need for backticks.
      render: Shell
