# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from emulations.utils import distributed_pb2 as emulations_dot_utils_dot_distributed__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in emulations/utils/distributed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.stream_stream(
                '/emulations.utils.distributed.NodeService/Run',
                request_serializer=emulations_dot_utils_dot_distributed__pb2.RunRequest.SerializeToString,
                response_deserializer=emulations_dot_utils_dot_distributed__pb2.RunResponse.FromString,
                _registered_method=True)
        self.RunReturn = channel.stream_stream(
                '/emulations.utils.distributed.NodeService/RunReturn',
                request_serializer=emulations_dot_utils_dot_distributed__pb2.RunRequest.SerializeToString,
                response_deserializer=emulations_dot_utils_dot_distributed__pb2.RunResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Run(self, request_iterator, context):
        """run a routine on node's context, save the return values as object refs,
        return the object refs to the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunReturn(self, request_iterator, context):
        """run a routine on node's context, return the object directly.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.stream_stream_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=emulations_dot_utils_dot_distributed__pb2.RunRequest.FromString,
                    response_serializer=emulations_dot_utils_dot_distributed__pb2.RunResponse.SerializeToString,
            ),
            'RunReturn': grpc.stream_stream_rpc_method_handler(
                    servicer.RunReturn,
                    request_deserializer=emulations_dot_utils_dot_distributed__pb2.RunRequest.FromString,
                    response_serializer=emulations_dot_utils_dot_distributed__pb2.RunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emulations.utils.distributed.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emulations.utils.distributed.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Run(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/emulations.utils.distributed.NodeService/Run',
            emulations_dot_utils_dot_distributed__pb2.RunRequest.SerializeToString,
            emulations_dot_utils_dot_distributed__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunReturn(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/emulations.utils.distributed.NodeService/RunReturn',
            emulations_dot_utils_dot_distributed__pb2.RunRequest.SerializeToString,
            emulations_dot_utils_dot_distributed__pb2.RunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
