# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: emulations/utils/distributed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'emulations/utils/distributed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"emulations/utils/distributed.proto\x12\x1c\x65mulations.utils.distributed\"\x1a\n\nRunRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1b\n\x0bRunResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xd7\x01\n\x0bNodeService\x12`\n\x03Run\x12(.emulations.utils.distributed.RunRequest\x1a).emulations.utils.distributed.RunResponse\"\x00(\x01\x30\x01\x12\x66\n\tRunReturn\x12(.emulations.utils.distributed.RunRequest\x1a).emulations.utils.distributed.RunResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'emulations.utils.distributed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RUNREQUEST']._serialized_start=68
  _globals['_RUNREQUEST']._serialized_end=94
  _globals['_RUNRESPONSE']._serialized_start=96
  _globals['_RUNRESPONSE']._serialized_end=123
  _globals['_NODESERVICE']._serialized_start=126
  _globals['_NODESERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
